name: Test and build our app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test

  build:
    name: Build the app
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checout repo
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm ci
      - name: Build dependecies
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: dist

  deploy:
    name: Deploy the app
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checout repo
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project intercontinental-tic-tac-toe   
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

